### PR TITLE
feature: add support for crate fs_err

### PR DESCRIPTION
**Pull request by beckend**
Support: https://crates.io/crates/fs-err

### CODE REVIEW

**Review by al8n — CHANGES_REQUESTED** [review]
Thanks! Please make CI work.

**Comment by beckend** [comment]
```shell
❯ cargo test --all-features
running 52 tests
test file_ext::async_impl::fs_err_tokio_impl::test::filesystem_space ... ok
test file_ext::async_impl::fs_err_tokio_impl::test::lock_cleanup ... ok
test file_ext::async_impl::fs_err_tokio_impl::test::lock_exclusive ... ok
test file_ext::async_impl::fs_err_tokio_impl::test::allocate ... ok
test file_ext::async_impl::fs_err_tokio_impl::test::lock_shared ... ok
test file_ext::async_impl::smol_impl::test::filesystem_space ... ok
test file_ext::async_impl::smol_impl::test::lock_exclusive ... ok
test file_ext::async_impl::smol_impl::test::lock_cleanup ... ok
test file_ext::async_impl::tokio_impl::test::filesystem_space ... ok
test file_ext::async_impl::smol_impl::test::allocate ... ok
test file_ext::async_impl::smol_impl::test::lock_shared ... ok
test file_ext::sync_impl::fs_err_impl::test::bench_available_space ... ok
test file_ext::sync_impl::fs_err_impl::test::allocate ... ok
test file_ext::async_impl::tokio_impl::test::lock_cleanup ... ok
test file_ext::async_impl::async_std_impl::test::filesystem_space ... ok
test file_ext::sync_impl::fs_err_impl::test::bench_file_create ... ok
test file_ext::async_impl::async_std_impl::test::lock_cleanup ... ok
test file_ext::sync_impl::fs_err_impl::test::bench_file_truncate ... ok
test file_ext::async_impl::async_std_impl::test::lock_exclusive ... ok
test file_ext::async_impl::async_std_impl::test::lock_shared ... ok
test file_ext::sync_impl::fs_err_impl::test::filesystem_space ... ok
test file_ext::async_impl::tokio_impl::test::lock_shared ... ok
test file_ext::sync_impl::fs_err_impl::test::bench_free_space ... ok
test file_ext::sync_impl::fs_err_impl::test::lock_cleanup ... ok
test file_ext::async_impl::tokio_impl::test::lock_exclusive ... ok
test file_ext::async_impl::async_std_impl::test::allocate ... ok
test file_ext::sync_impl::fs_err_impl::test::bench_total_space ... ok
test file_ext::sync_impl::fs_err_impl::test::bench_lock_unlock ... ok
test file_ext::async_impl::tokio_impl::test::allocate ... ok
test file_ext::sync_impl::fs_err_impl::test::lock_exclusive ... ok
test file_ext::sync_impl::fs_err_impl::test::lock_shared ... ok
test file_ext::sync_impl::std_impl::test::bench_available_space ... ok
test file_ext::sync_impl::std_impl::test::bench_file_create ... ok
test file_ext::sync_impl::std_impl::test::allocate ... ok
test file_ext::sync_impl::std_impl::test::bench_file_truncate ... ok
test file_ext::sync_impl::std_impl::test::bench_free_space ... ok
test file_ext::sync_impl::std_impl::test::bench_lock_unlock ... ok
test file_ext::sync_impl::std_impl::test::bench_total_space ... ok
test file_ext::sync_impl::std_impl::test::filesystem_space ... ok
test file_ext::sync_impl::std_impl::test::lock_cleanup ... ok
test file_ext::sync_impl::std_impl::test::lock_exclusive ... ok
test file_ext::sync_impl::std_impl::test::lock_shared ... ok
test unix::async_impl::async_std_impl::test::lock_replace ... ok
test unix::async_impl::smol_impl::test::lock_replace ... ok
test unix::sync_impl::fs_err_impl::test::lock_replace ... ok
test unix::sync_impl::std_impl::test::lock_replace ... ok
test unix::async_impl::fs_err_tokio_impl::test::lock_replace ... ok
test unix::async_impl::tokio_impl::test::lock_replace ... ok
test file_ext::sync_impl::fs_err_impl::test::bench_file_allocate ... ok
test file_ext::sync_impl::std_impl::test::bench_file_allocate ... ok
test file_ext::sync_impl::fs_err_impl::test::bench_allocated_size ... ok
test file_ext::sync_impl::std_impl::test::bench_allocated_size ... ok

test result: ok. 52 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

   Doc-tests fs4

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

```

**Comment by beckend** [comment]
I don't have windows, I hope CI can test that.

**Comment by beckend** [comment]
@al8n How can I re run CI, I need to re run it many times to fix the errors.

**Comment by beckend** [comment]
Never mind, I am running https://github.com/nektos/act
Working on the fixes.

**Comment by beckend** [comment]
```shell
❯ act -P ubuntu-latest=-self-hosted
INFO[0000] Using docker host 'unix:///run/user/1000/podman/podman.sock', and daemon socket 'unix:///run/user/1000/podman/podman.sock'
[CI/unit tests-1] 🚧  Skipping unsupported platform -- Try running with `-P macos-latest=...`
[CI/unit tests-3] 🚧  Skipping unsupported platform -- Try running with `-P macos-latest=...`
[CI/unit tests-2] 🚧  Skipping unsupported platform -- Try running with `-P windows-latest=...`
[CI/minrust     ] ⭐ Run Main actions/checkout@v3
[CI/clippy      ] ⭐ Run Main actions/checkout@v3
[CI/rustfmt     ] ⭐ Run Main actions/checkout@v3
[CI/minrust     ]   ✅  Success - Main actions/checkout@v3
[CI/clippy      ]   ✅  Success - Main actions/checkout@v3
[CI/rustfmt     ]   ✅  Success - Main actions/checkout@v3
[CI/clippy      ] ⭐ Run Main Apply clippy lints
[CI/minrust     ] ⭐ Run Main Install Rust
[CI/rustfmt     ] ⭐ Run Main Install Rust
| info: syncing channel updates for '1.75.0-x86_64-unknown-linux-gnu'
| info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
|     Updating crates.io index
|
|
|   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.80.0 (051478957 2024-07-21)
|
| info: self-update is disabled for this build of rustup
| info: any updates to rustup will need to be fetched with your system package manager
|   1.75.0-x86_64-unknown-linux-gnu unchanged - rustc 1.75.0 (82e1608df 2023-12-21)
|
| info: self-update is disabled for this build of rustup
| info: any updates to rustup will need to be fetched with your system package manager
| info: using existing install for '1.75.0-x86_64-unknown-linux-gnu'
| info: using existing install for 'stable-x86_64-unknown-linux-gnu'
| info: default toolchain set to '1.75.0-x86_64-unknown-linux-gnu'
|
| info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'
|
|   1.75.0-x86_64-unknown-linux-gnu unchanged - rustc 1.75.0 (82e1608df 2023-12-21)
|
|   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.80.0 (051478957 2024-07-21)
|
[CI/minrust     ]   ✅  Success - Main Install Rust
[CI/rustfmt     ]   ✅  Success - Main Install Rust
[CI/minrust     ] ⭐ Run Main Check
[CI/rustfmt     ] ⭐ Run Main Check formatting
[CI/rustfmt     ]   ✅  Success - Main Check formatting
[CI/rustfmt     ] Cleaning up container for job rustfmt
[CI/rustfmt     ] 🏁  Job succeeded
|     Blocking waiting for file lock on package cache
|     Updating crates.io index
|     Blocking waiting for file lock on package cache
|     Blocking waiting for file lock on package cache
|      Locking 129 packages to latest compatible versions
|     Blocking waiting for file lock on package cache
|       Adding addr2line v0.22.0 (latest: v0.24.1)
|       Adding async-channel v1.9.0 (latest: v2.3.1)
|       Adding async-io v1.13.0 (latest: v2.3.3)
|       Adding async-lock v2.8.0 (latest: v3.4.0)
|       Adding bitflags v1.3.2 (latest: v2.6.0)
|       Adding event-listener v2.5.3 (latest: v5.3.1)
|       Adding fastrand v1.9.0 (latest: v2.1.0)
|       Adding futures-lite v1.13.0 (latest: v2.3.0)
|       Adding gimli v0.29.0 (latest: v0.31.0)
|       Adding gloo-timers v0.2.6 (latest: v0.3.0)
|       Adding hermit-abi v0.3.9 (latest: v0.4.0)
|       Adding io-lifetimes v1.0.11 (latest: v2.0.3)
|       Adding linux-raw-sys v0.3.8 (latest: v0.6.4)
|       Adding linux-raw-sys v0.4.14 (latest: v0.6.4)
|       Adding polling v2.8.0 (latest: v3.7.2)
|       Adding rand v0.4.6 (latest: v0.8.5)
|       Adding rand_core v0.3.1 (latest: v0.6.4)
|       Adding rand_core v0.4.2 (latest: v0.6.4)
|       Adding rdrand v0.4.0 (latest: v0.8.3)
|       Adding remove_dir_all v0.5.3 (latest: v0.8.3)
|       Adding rustix v0.37.27 (latest: v0.38.34)
|       Adding socket2 v0.4.10 (latest: v0.5.7)
|       Adding syn v1.0.109 (latest: v2.0.72)
|       Adding wasi v0.11.0+wasi-snapshot-preview1 (latest: v0.13.1+wasi-0.2.0)
|       Adding windows-sys v0.48.0 (latest: v0.52.0)
|       Adding windows-targets v0.48.5 (latest: v0.52.6)
|       Adding windows_aarch64_gnullvm v0.48.5 (latest: v0.52.6)
|       Adding windows_aarch64_msvc v0.48.5 (latest: v0.52.6)
|       Adding windows_i686_gnu v0.48.5 (latest: v0.52.6)
|       Adding windows_i686_msvc v0.48.5 (latest: v0.52.6)
|       Adding windows_x86_64_gnu v0.48.5 (latest: v0.52.6)
|       Adding windows_x86_64_gnullvm v0.48.5 (latest: v0.52.6)
|       Adding windows_x86_64_msvc v0.48.5 (latest: v0.52.6)
|     Blocking waiting for file lock on package cache
|     Blocking waiting for file lock on package cache
|     Checking pin-project-lite v0.2.14
|    Compiling autocfg v1.3.0
|    Compiling crossbeam-utils v0.8.20
|     Checking parking v2.2.0
|     Checking futures-core v0.3.30
|     Checking futures-io v0.3.30
|     Checking fastrand v2.1.0
|    Compiling libc v0.2.155
|     Checking cfg-if v1.0.0
|    Compiling rustix v0.38.34
|     Checking bitflags v2.6.0
|     Checking linux-raw-sys v0.4.14
|    Compiling rustix v0.38.34
|     Checking linux-raw-sys v0.4.14
|     Checking bitflags v2.6.0
|     Checking tracing-core v0.1.32
|     Checking async-task v4.7.1
|     Checking atomic-waker v1.1.2
|    Compiling io-lifetimes v1.0.11
|     Checking value-bag v1.9.0
|    Compiling rustix v0.37.27
|    Compiling slab v0.4.9
|    Compiling polling v2.8.0
|     Checking event-listener v2.5.3
|    Compiling async-io v1.13.0
|     Checking fastrand v1.9.0
|     Checking futures-lite v2.3.0
|     Checking tracing v0.1.40
|     Checking piper v0.2.3
|     Checking waker-fn v1.2.0
|     Checking memchr v2.7.4
|     Checking linux-raw-sys v0.3.8
|     Checking log v0.4.22
|     Checking bitflags v1.3.2
|     Checking async-lock v2.8.0
|    Compiling fs-err v2.11.0
|     Checking once_cell v1.19.0
|     Checking tokio v1.39.2
|     Checking pin-utils v0.1.0
|     Checking kv-log-macro v1.0.7
|     Checking concurrent-queue v2.5.0
|     Checking futures-lite v1.13.0
|     Checking event-listener v5.3.1
|     Checking async-executor v1.13.0
|     Checking async-channel v1.9.0
|     Checking event-listener-strategy v0.5.2
|     Checking async-lock v3.4.0
|     Checking async-channel v2.3.1
|     Checking fs4 v0.8.4 (/home/admin/.cache/act/e8b3ea6c30dd2b94/hostexecutor)
|     Checking signal-hook-registry v1.4.2
|     Checking socket2 v0.4.10
|     Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.21s
|     Checking blocking v1.6.1
[CI/minrust     ]   ✅  Success - Main Check
[CI/minrust     ] Cleaning up container for job minrust
[CI/minrust     ] 🏁  Job succeeded
|     Checking async-fs v2.1.2
|     Checking polling v3.7.2
|     Checking async-io v2.3.3
|     Checking async-signal v0.2.9
|     Checking async-net v2.0.0
|     Checking async-global-executor v2.4.1
|     Checking async-process v2.2.3
|     Checking async-std v1.12.0
|     Checking smol v2.0.0
|     Checking fs4 v0.8.4 (/home/admin/.cache/act/e98acc54468e4e86/hostexecutor)
|     Finished dev [unoptimized + debuginfo] target(s) in 3.06s
[CI/clippy      ]   ✅  Success - Main Apply clippy lints
[CI/clippy      ] Cleaning up container for job clippy
[CI/clippy      ] 🏁  Job succeeded
```

**Comment by beckend** [comment]
I refactored the tests, no more copy pasta:
[`b86d2e5` (#24)](https://github.com/al8n/fs4-rs/pull/24/commits/b86d2e5bbc73a18d6b4ec8d9616a292ba6876f41)

**Comment by beckend** [comment]
@al8n done now, here is the CI on my fork:

https://github.com/beckend/fs4-rs/actions/runs/10125351877/job/28000812397?pr=2

The codecov fails because I don't have a token.

**Review by al8n — APPROVED** [review]
Thank you very much!

**Pull request merged**
